[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/calvin_sports.py"
name = "Calvin (Sports)"
icon = "ğŸ€"

[[pages]]
path = "pages/felix_productivity.py"
name = "Felix (Producivity)"
icon = "ğŸ‘¨â€ğŸ’»"

[[pages]]
path = "pages/oscar_content_creation.py"
name = "Oscar (Content Creation)"
icon = "âœï¸"